
CREATE TABLE FeedBack(
FeedBackId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Rating FLOAT NOT NULL,
Comment VARCHAR(MAX) NOT NULL,
UserId INT FOREIGN KEY (UserId) REFERENCES Users(UserId),
BookId INT FOREIGN KEY (BookId) REFERENCES Books(BookId)
)

SELECT * FROM FeedBack

GO
CREATE PROCEDURE Add_FeedBack @Rating FLOAT, @Comment VARCHAR(MAX), @BookId INT, @UserId INT
AS
BEGIN
INSERT INTO FeedBack VALUES(@Rating, @Comment, @UserId, @BookId)
END

GO
ALTER PROCEDURE Get_Feedback @BookId INT
AS
BEGIN
SELECT Rating, Comment, UserName FROM FeedBack AS FB INNER JOIN Users AS UR ON FB.UserId = UR.UserId WHERE BookId = @BookId
END


